name: cd

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: "1.25.1"

      - name: Build app
        run: ./scripts/buildprod.sh

# 1. Authenticate using Service Account Key JSON
      - id: auth
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      # 2. Install and configure the gcloud CLI
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: gcloud builds submit
        run: gcloud builds submit --tag us-central1-docker.pkg.dev/notely-503509/notely-ar-repo/notely:v1 .